export interface CuratedCourse {
  id: string;
  title: string;
  platform: string;
  instructor: string;
  rating: number;
  learners: string;
  duration: string;
  level: "Beginner" | "Intermediate" | "Advanced";
  certificate: string;
  skills: string[];
  link: string;
  domain: "Tech" | "Finance" | "Marketing" | "HR" | "MBA/Business" | "Commerce";
  subDomain: string;
}

export const PRESET_CURATED_COURSES: CuratedCourse[] = [
  // ==================== TECH (25 Courses) ====================
  {
    id: "tech-1",
    title: "React Complete Guide & Redux Toolkit Masterclass",
    platform: "Udemy",
    instructor: "Maximilian Schwarzmüller",
    rating: 4.8,
    learners: "520K+",
    duration: "38 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["React", "Redux", "Hooks", "API Integration", "State Management"],
    link: "https://www.udemy.com/course/react-the-complete-guide-incl-redux/",
    domain: "Tech",
    subDomain: "Frontend"
  },
  {
    id: "tech-2",
    title: "TypeScript Essentials and Advanced Architecture Patterns",
    platform: "Udemy",
    instructor: "Stephen Grider",
    rating: 4.9,
    learners: "95K+",
    duration: "18 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["TypeScript", "OOP", "Generics", "Vite", "Advanced Coding"],
    link: "https://www.udemy.com/course/typescript-the-complete-developers-guide/",
    domain: "Tech",
    subDomain: "Frontend"
  },
  {
    id: "tech-3",
    title: "HTML5 and CSS3: Ultimate Responsive Layouts & Variables",
    platform: "Udemy",
    instructor: "Jonas Schmedtmann",
    rating: 4.8,
    learners: "380K+",
    duration: "37 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["HTML", "Flexbox", "CSS Grid", "Responsive Design", "Sass"],
    link: "https://www.udemy.com/course/design-and-develop-a-killer-website-with-html5-and-css3/",
    domain: "Tech",
    subDomain: "Frontend"
  },
  {
    id: "tech-4",
    title: "Next.js Production-Ready App Blueprint (React 19 Hooks)",
    platform: "Udemy",
    instructor: "Maximilian Schwarzmüller",
    rating: 4.9,
    learners: "85K+",
    duration: "44 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Next.js", "Server Components", "SEO Optimization", "Vercel Deployments"],
    link: "https://www.udemy.com/course/nextjs-react-the-complete-guide/",
    domain: "Tech",
    subDomain: "Frontend"
  },
  {
    id: "tech-5",
    title: "Tailwind CSS: Complete Guide From HTML to Interactive UI Assets",
    platform: "YouTube",
    instructor: "Brad Traversy",
    rating: 4.7,
    learners: "290K+",
    duration: "4 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Tailwind CSS", "Flexbox", "Responsive Design", "Utility Typography"],
    link: "https://www.youtube.com/results?search_query=tailwind+css+full+course",
    domain: "Tech",
    subDomain: "Frontend"
  },
  {
    id: "tech-6",
    title: "Node.js Complete Guide: Express, SQL & Mongoose Operations",
    platform: "Udemy",
    instructor: "Jonas Schmedtmann",
    rating: 4.8,
    learners: "240K+",
    duration: "42 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Node.js", "Express.js", "REST APIs", "Mongoose", "MongoDB"],
    link: "https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/",
    domain: "Tech",
    subDomain: "Backend"
  },
  {
    id: "tech-7",
    title: "The Ultimate SQL Bootcamp: Database Admin & Master Queries",
    platform: "Udemy",
    instructor: "Jose Portilla",
    rating: 4.7,
    learners: "410K+",
    duration: "9 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["SQL", "Query Optimization", "PostgreSQL", "Database Analysis"],
    link: "https://www.udemy.com/course/the-complete-sql-bootcamp/",
    domain: "Tech",
    subDomain: "Backend"
  },
  {
    id: "tech-8",
    title: "Go: Complete Developer's Blueprint (Golang Backend Tuning)",
    platform: "Udemy",
    instructor: "Stephen Grider",
    rating: 4.8,
    learners: "65K+",
    duration: "11 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Go (Golang)", "Concurrency", "REST APIs", "Performance Optimization"],
    link: "https://www.udemy.com/course/go-the-complete-developers-guide/",
    domain: "Tech",
    subDomain: "Backend"
  },
  {
    id: "tech-9",
    title: "Python Django & Flask Web Development Core Frameworks Roadmap",
    platform: "Coursera",
    instructor: "William Vincent",
    rating: 4.6,
    learners: "80K+",
    duration: "3 Months",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Django", "Flask", "Python Backend", "SQLAlchemy", "ORM"],
    link: "https://www.coursera.org/learn/django-database-web-development",
    domain: "Tech",
    subDomain: "Backend"
  },
  {
    id: "tech-10",
    title: "Supervised Machine Learning: Regression and Classification Tools",
    platform: "Coursera",
    instructor: "Andrew Ng",
    rating: 4.9,
    learners: "1.2M+",
    duration: "33 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Machine Learning", "Python Core", "Regression", "Classification Analysis"],
    link: "https://www.coursera.org/learn/machine-learning",
    domain: "Tech",
    subDomain: "AI/ML"
  },
  {
    id: "tech-11",
    title: "Deep Learning Specialization: RNNs, CNNS, tuning & setup",
    platform: "Coursera",
    instructor: "Andrew Ng",
    rating: 4.9,
    learners: "480K+",
    duration: "3 Months",
    level: "Advanced",
    certificate: "Available",
    skills: ["Deep Learning", "TensorFlow", "Neural Networks", "NLP Modelling"],
    link: "https://www.coursera.org/specializations/deep-learning",
    domain: "Tech",
    subDomain: "AI/ML"
  },
  {
    id: "tech-12",
    title: "Generative AI with Large Language Models Professional Strategy",
    platform: "Coursera",
    instructor: "Sharon Zhou",
    rating: 4.8,
    learners: "150K+",
    duration: "16 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["LLMs", "Generative AI", "Fine-tuning Systems", "Prompt Engineering"],
    link: "https://www.coursera.org/learn/generative-ai-with-llms",
    domain: "Tech",
    subDomain: "AI/ML"
  },
  {
    id: "tech-13",
    title: "IBM Data Science Professional Career Certification",
    platform: "Coursera",
    instructor: "IBM Global Faculty",
    rating: 4.7,
    learners: "890K+",
    duration: "5 Months",
    level: "Beginner",
    certificate: "Available",
    skills: ["Data Science", "Python Engine", "SQL", "Pandas", "Matplotlib Dash"],
    link: "https://www.coursera.org/professional-certificates/ibm-data-science",
    domain: "Tech",
    subDomain: "Data Science"
  },
  {
    id: "tech-14",
    title: "Advanced Analytics & Business Intelligence Dashboarding tools",
    platform: "Udemy",
    instructor: "Kirill Eremenko",
    rating: 4.7,
    learners: "110K+",
    duration: "21 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Tableau BI", "Data Wrangling", "Dashboarding Design", "Insights Pipeline"],
    link: "https://www.udemy.com/course/tableau10/",
    domain: "Tech",
    subDomain: "Data Science"
  },
  {
    id: "tech-15",
    title: "Google Cybersecurity Professional Career Certificate Program",
    platform: "Coursera",
    instructor: "Google Career Experts",
    rating: 4.8,
    learners: "320K+",
    duration: "6 Months",
    level: "Beginner",
    certificate: "Available",
    skills: ["Linux Terminal", "Security Audit Planning", "SIEM Dashboards", "Network Intrusion"],
    link: "https://www.coursera.org/professional-certificates/google-cybersecurity",
    domain: "Tech",
    subDomain: "Cybersecurity"
  },
  {
    id: "tech-16",
    title: "CompTIA Security+ Exam Preparation Premium Prep Boot Camp",
    platform: "Udemy",
    instructor: "Jason Dion",
    rating: 4.8,
    learners: "160K+",
    duration: "30 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Cryptography Basics", "Threat Assessment", "Exam Readiness", "Protocol Defense"],
    link: "https://www.udemy.com/course/securityplus/",
    domain: "Tech",
    subDomain: "Cybersecurity"
  },
  {
    id: "tech-17",
    title: "AWS Certified Cloud Practitioner Ultimate Training Program",
    platform: "Udemy",
    instructor: "Stephane Maarek",
    rating: 4.8,
    learners: "540K+",
    duration: "15 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["AWS Platform", "EC2 Compute", "S3 Storage", "IAM Management", "Cloud Pricing"],
    link: "https://www.udemy.com/course/aws-certified-cloud-practitioner-training-course/",
    domain: "Tech",
    subDomain: "Cloud"
  },
  {
    id: "tech-18",
    title: "Docker and Kubernetes: Microservice Pipelines and DevOps",
    platform: "Udemy",
    instructor: "Stephen Grider",
    rating: 4.9,
    learners: "280K+",
    duration: "22 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Docker Core", "Kubernetes Clusters", "CI/CD Orchestration", "Microservices Networking"],
    link: "https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/",
    domain: "Tech",
    subDomain: "Cloud"
  },
  {
    id: "tech-19",
    title: "Google Cloud Platform Associate Solutions Engineer Blueprint",
    platform: "Udemy",
    instructor: "Ranga Kanamarlapudi",
    rating: 4.7,
    learners: "95K+",
    duration: "18 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["GCP Computing", "Kubernetes Engine", "IAM Security Policy", "Cloud Networks"],
    link: "https://www.udemy.com/course/google-cloud-associate-cloud-engineer-certification/",
    domain: "Tech",
    subDomain: "Cloud"
  },
  {
    id: "tech-20",
    title: "Google UX Design Professional Certification Roadmap",
    platform: "Coursera",
    instructor: "Google UX Research Team",
    rating: 4.8,
    learners: "590K+",
    duration: "6 Months",
    level: "Beginner",
    certificate: "Available",
    skills: ["Figma Design", "User Interviewing", "Wireframing Prototyping", "Design Strategy"],
    link: "https://www.coursera.org/professional-certificates/google-ux-design",
    domain: "Tech",
    subDomain: "UI/UX"
  },
  {
    id: "tech-21",
    title: "User Experience Design Masterclass: Adobe and Figma",
    platform: "Udemy",
    instructor: "Joe Natoli",
    rating: 4.7,
    learners: "120K+",
    duration: "24 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["UX Design Audit", "Figma Components", "Wireframe Analysis", "Cognitive Layouts"],
    link: "https://www.udemy.com/course/user-experience-design-fundamentals-course/",
    domain: "Tech",
    subDomain: "UI/UX"
  },
  {
    id: "tech-22",
    title: "Advanced Angular & RxJS Mastery Flow Components",
    platform: "Udemy",
    instructor: "Todd Motto",
    rating: 4.6,
    learners: "40K+",
    duration: "22 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Angular Architecture", "RxJS Operators", "Custom States", "Testing Workflows"],
    link: "https://www.udemy.com/course/angular-masterclass/",
    domain: "Tech",
    subDomain: "Frontend"
  },
  {
    id: "tech-23",
    title: "Spring Boot, JPA & Microservices Enterprise Java Architect",
    platform: "Udemy",
    instructor: "Chad Darby",
    rating: 4.7,
    learners: "150K+",
    duration: "41 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Spring Boot", "Enterprise Microservices", "Spring Security", "JPA Registry"],
    link: "https://www.udemy.com/course/spring-hibernate-tutorial-to-html-dev-to-unlimited/",
    domain: "Tech",
    subDomain: "Backend"
  },
  {
    id: "tech-24",
    title: "R Programming Language Bootcamp for Statisticians & NLP Data",
    platform: "Coursera",
    instructor: "Johns Hopkins Faculty",
    rating: 4.5,
    learners: "210K+",
    duration: "4 Weeks",
    level: "Beginner",
    certificate: "Available",
    skills: ["R Engine", "Data Wrangling", "GGPlot2 Visuals", "Inference Modeling"],
    link: "https://www.coursera.org/learn/r-programming",
    domain: "Tech",
    subDomain: "Data Science"
  },
  {
    id: "tech-25",
    title: "Natural Language Processing (NLP) Transformers pipeline",
    platform: "Coursera",
    instructor: "HuggingFace Core Team",
    rating: 4.8,
    learners: "75K+",
    duration: "18 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Transformer Architecture", "HuggingFace pipelines", "Attention Matrices", "Sentiment Tuners"],
    link: "https://www.coursera.org/learn/transformers-nlp",
    domain: "Tech",
    subDomain: "AI/ML"
  },

  // ==================== FINANCE (25 Courses) ====================
  {
    id: "fin-1",
    title: "Financial Analysis & Decision Making Executive Specialization",
    platform: "Coursera",
    instructor: "Prof. Keith Robertson",
    rating: 4.8,
    learners: "120K+",
    duration: "6 Months",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Financial Analysis", "Capital Budgeting", "Ratio Assessments", "Investment Decisions"],
    link: "https://www.coursera.org/specializations/financial-management",
    domain: "Finance",
    subDomain: "Financial Analysis"
  },
  {
    id: "fin-2",
    title: "Financial Modeling & Valuation Analyst (FMVA®) Blueprint",
    platform: "Udemy",
    instructor: "Corporate Finance Institute",
    rating: 4.9,
    learners: "180K+",
    duration: "35 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["DCF Modeling", "Valuation Analysis", "Three Statement Models", "Leveraged Buyouts"],
    link: "https://www.udemy.com/course/financial-modeling-for-beginners/",
    domain: "Finance",
    subDomain: "Financial Modeling"
  },
  {
    id: "fin-3",
    title: "Microsoft Excel: Advanced Formulation & Analytical Datatables",
    platform: "Udemy",
    instructor: "Chris Dutton",
    rating: 4.8,
    learners: "450K+",
    duration: "9 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Excel VLOOKUP/XLOOKUP", "Pivot Tables", "Dynamic Array Formulas", "Financial Structuring"],
    link: "https://www.udemy.com/course/microsoft-excel-formulas-functions/",
    domain: "Finance",
    subDomain: "Excel"
  },
  {
    id: "fin-4",
    title: "Power BI Complete Masterclass: Enterprise Data Analysis",
    platform: "Coursera",
    instructor: "Microsoft Press Team",
    rating: 4.7,
    learners: "95K+",
    duration: "24 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Power BI Engine", "DAX Formulas", "Data Modeling", "Dashboard Architecture"],
    link: "https://www.coursera.org/learn/power-bi-data-analytics",
    domain: "Finance",
    subDomain: "Power BI"
  },
  {
    id: "fin-5",
    title: "Investment Analysis & Corporate Asset Portfolio Management",
    platform: "Udemy",
    instructor: "Dr. Manish Kumar",
    rating: 4.8,
    learners: "70K+",
    duration: "12 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Portfolio Optimization", "Modern Portfolio Theory", "Risk Benchmarking", "Asset Allocation"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Finance",
    subDomain: "Financial Analysis"
  },
  {
    id: "fin-6",
    title: "Introduction to Corporate Finance & Structural Markets",
    platform: "Coursera",
    instructor: "Prof. Franklin Allen",
    rating: 4.8,
    learners: "220K+",
    duration: "10 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Corporate Finance", "Time Value of Money", "Investment Appraisal", "Debt Capital"],
    link: "https://www.coursera.org/learn/wharton-finance",
    domain: "Finance",
    subDomain: "Financial Modeling"
  },
  {
    id: "fin-7",
    title: "Economics of Banking & Global Monetary Policies",
    platform: "Coursera",
    instructor: "Prof. Andrew Sentance",
    rating: 4.7,
    learners: "60K+",
    duration: "16 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Commercial Banking", "Monetary Policy", "Interest Economics", "Liquidity Management"],
    link: "https://www.coursera.org/learn/money-banking",
    domain: "Finance",
    subDomain: "Banking"
  },
  {
    id: "fin-8",
    title: "FinTech: Foundations & Applications of Financial Technology",
    platform: "Coursera",
    instructor: "Wharton Business School",
    rating: 4.8,
    learners: "130K+",
    duration: "4 Months",
    level: "Beginner",
    certificate: "Available",
    skills: ["FinTech", "Blockchain Networks", "API Payments", "Robo-Advising Engines"],
    link: "https://www.coursera.org/specializations/financial-technology- Wharton",
    domain: "Finance",
    subDomain: "FinTech"
  },
  {
    id: "fin-9",
    title: "Advanced Financial Modeling for Investment Banking",
    platform: "Udemy",
    instructor: "Wall Street Prep Specialists",
    rating: 4.9,
    learners: "45K+",
    duration: "20 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["LBO Modeling", "M&A Analytics", "Sensitivity Datatables", "Pitchbook Formatting"],
    link: "https://www.udemy.com/course/financial-modeling-for-beginners/",
    domain: "Finance",
    subDomain: "Financial Modeling"
  },
  {
    id: "fin-10",
    title: "Data Analysis and Modeling using Excel Power Query",
    platform: "Udemy",
    instructor: "Kyle Pew",
    rating: 4.8,
    learners: "190K+",
    duration: "15 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Power Query", "M Language", "ETL Pipelines", "Data Structuring"],
    link: "https://www.udemy.com/course/microsoft-excel-formulas-functions/",
    domain: "Finance",
    subDomain: "Excel"
  },
  {
    id: "fin-11",
    title: "The Mechanics of Investment Banking & Loan Syndications",
    platform: "Coursera",
    instructor: "Geneva Finance Faculty",
    rating: 4.6,
    learners: "35K+",
    duration: "18 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Investment Banking", "Syndicated Loans", "Capital Restructuring", "IPO Underwriting"],
    link: "https://www.coursera.org/learn/money-banking",
    domain: "Finance",
    subDomain: "Banking"
  },
  {
    id: "fin-12",
    title: "Introduction to Wealth Management and Financial Advisory",
    platform: "Udemy",
    instructor: "Financial Training Association",
    rating: 4.7,
    learners: "55K+",
    duration: "6 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Wealth Management", "Asset Preservation", "Advisory Ethics", "Tax Shield Strategies"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Finance",
    subDomain: "Banking"
  },
  {
    id: "fin-13",
    title: "Decentralized Finance (DeFi) & Smart Contracts Strategy",
    platform: "Coursera",
    instructor: "Cam Harvey (Duke University)",
    rating: 4.9,
    learners: "82K+",
    duration: "12 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["DeFi Economics", "Ethereum Protocols", "Automated Market Makers", "Liquidity Pools"],
    link: "https://www.coursera.org/specializations/financial-technology- Wharton",
    domain: "Finance",
    subDomain: "FinTech"
  },
  {
    id: "fin-14",
    title: "Quantitative Finance: Algorithmic Trading with Python",
    platform: "Udemy",
    instructor: "Dr. Yves Hilpisch",
    rating: 4.8,
    learners: "320K+",
    duration: "25 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Quantitative Finance", "Alpha Generation", "Backtesting Scripts", "Pandas Finance"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Finance",
    subDomain: "FinTech"
  },
  {
    id: "fin-15",
    title: "Advanced Power BI: DAX Calculations & Performance Tuning",
    platform: "Udemy",
    instructor: "Enterprise DNA Experts",
    rating: 4.8,
    learners: "50K+",
    duration: "14 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["DAX Query Tuning", "Filter Context", "Variables in DAX", "DirectQuery Optimization"],
    link: "https://www.udemy.com/course/microsoft-excel-formulas-functions/",
    domain: "Finance",
    subDomain: "Power BI"
  },
  {
    id: "fin-16",
    title: "Credit Risk Analysis & Debt Covenant Structuring",
    platform: "Coursera",
    instructor: "Delft University of Technology",
    rating: 4.7,
    learners: "28K+",
    duration: "22 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Credit Risk Models", "Covenants Analysis", "Probability of Default", "Basel III Norms"],
    link: "https://www.coursera.org/learn/money-banking",
    domain: "Finance",
    subDomain: "Banking"
  },
  {
    id: "fin-17",
    title: "Fundamental Analysis: Reading Corporate Balance Sheets",
    platform: "Udemy",
    instructor: "Sven Carlin",
    rating: 4.7,
    learners: "105K+",
    duration: "8 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Fundamental Analysis", "Balance Sheets Audit", "Capital Adequacy", "Earnings Yield"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Finance",
    subDomain: "Financial Analysis"
  },
  {
    id: "fin-18",
    title: "Excel Dashboard Design: Dynamic C-Suite Reporting Templates",
    platform: "Udemy",
    instructor: "Chandoo (Purna Duggirala)",
    rating: 4.9,
    learners: "115K+",
    duration: "12 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Interactive Charts", "Form Controls", "KPI Cards Design", "Conditional Formats"],
    link: "https://www.udemy.com/course/microsoft-excel-formulas-functions/",
    domain: "Finance",
    subDomain: "Excel"
  },
  {
    id: "fin-19",
    title: "Enterprise Power BI Data Warehouse Integration Strategy",
    platform: "Coursera",
    instructor: "Microsoft Learn experts",
    rating: 4.7,
    learners: "75K+",
    duration: "30 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Data Warehousing", "Synapse ETL Integration", "Role-Level Security", "Row Filters"],
    link: "https://www.coursera.org/learn/power-bi-data-analytics",
    domain: "Finance",
    subDomain: "Power BI"
  },
  {
    id: "fin-20",
    title: "Startup Valuation and Angel Investors Capital Structure",
    platform: "Coursera",
    instructor: "Younes Bensouda Mourri",
    rating: 4.8,
    learners: "44K+",
    duration: "10 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Startup Valuation", "First-round Cap Sheets", "Safes/Convertibles", "Equity dilution"],
    link: "https://www.coursera.org/learn/wharton-finance",
    domain: "Finance",
    subDomain: "Financial Modeling"
  },
  {
    id: "fin-21",
    title: "International Trade Finance and Letters of Credit Operations",
    platform: "Udemy",
    instructor: "Trade Finance Academy",
    rating: 4.6,
    learners: "22K+",
    duration: "9 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Letters of Credit", "Incoterms Rules", "Sovereign Bill Financing", "Guarantees Admin"],
    link: "https://www.udemy.com/course/financial-modeling-for-beginners/",
    domain: "Finance",
    subDomain: "Banking"
  },
  {
    id: "fin-22",
    title: "Central Banking, Inflation, and Yield Curves Forecasting",
    platform: "Coursera",
    instructor: "Yale University Faculty",
    rating: 4.9,
    learners: "90K+",
    duration: "14 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Yield Curve Analysis", "Quantitative Easing", "Inflation Indicators", "Macro-Modeling"],
    link: "https://www.coursera.org/learn/money-banking",
    domain: "Finance",
    subDomain: "Banking"
  },
  {
    id: "fin-23",
    title: "Financial Econometrics and Statistical Modeling Basics",
    platform: "Coursera",
    instructor: "Erasmus University Rotterdam",
    rating: 4.7,
    learners: "29K+",
    duration: "25 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Econometrics", "GARCH Models", "Regression Diagnostics", "Stochastic Calculus"],
    link: "https://www.coursera.org/specializations/financial-management",
    domain: "Finance",
    subDomain: "Financial Analysis"
  },
  {
    id: "fin-24",
    title: "Algorithmic Risk Management and Stress Testing matrices",
    platform: "Udemy",
    instructor: "FRM Coaches Guild",
    rating: 4.8,
    learners: "18K+",
    duration: "16 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Value at Risk (VaR)", "Monte Carlo Simulation", "Backtesting Engine", "Counterparty Stress"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Finance",
    subDomain: "FinTech"
  },
  {
    id: "fin-25",
    title: "Excel VBA Programmatic Trading Macro Automation",
    platform: "Udemy",
    instructor: "Daniel Strong",
    rating: 4.8,
    learners: "85K+",
    duration: "18 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Excel VBA Macros", "API Fetching Macros", "Event Handling Controls", "Userforms Layouts"],
    link: "https://www.udemy.com/course/microsoft-excel-formulas-functions/",
    domain: "Finance",
    subDomain: "Excel"
  },

  // ==================== MARKETING (25 Courses) ====================
  {
    id: "mkt-1",
    title: "Digital Marketing Specialist: Ultimate Masterclass Blueprint",
    platform: "Udemy",
    instructor: "Robby Miles",
    rating: 4.8,
    learners: "650K+",
    duration: "22 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Digital Marketing", "SEO Basics", "Email Campaigns", "Conversion Metrics"],
    link: "https://www.udemy.com/course/learn-digital-marketing-course/",
    domain: "Marketing",
    subDomain: "Digital Marketing"
  },
  {
    id: "mkt-2",
    title: "Google Analytics 4 (GA4) Analytics Specialist Certification",
    platform: "Coursera",
    instructor: "Google Marketing Experts",
    rating: 4.9,
    learners: "220K+",
    duration: "12 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["GA4 Tracking", "Cohort Analytics", "User Funnels", "Custom Dimensions"],
    link: "https://www.coursera.org/learn/google-analytics",
    domain: "Marketing",
    subDomain: "Analytics"
  },
  {
    id: "mkt-3",
    title: "SEO Foundations & Enterprise Technical Site Audit",
    platform: "Udemy",
    instructor: "Alex Genadinik",
    rating: 4.7,
    learners: "150K+",
    duration: "11 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["On-Page SEO", "Search Rankings", "SEM Rush Tool", "Backlinking Strategy"],
    link: "https://www.udemy.com/course/seo-get-targeted-traffic-to-your-website-optimized/",
    domain: "Marketing",
    subDomain: "SEO"
  },
  {
    id: "mkt-4",
    title: "Social Media Strategy and Organic Brand Funnels Roadmap",
    platform: "Coursera",
    instructor: "Meta Marketing Faculty",
    rating: 4.8,
    learners: "270K+",
    duration: "10 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Social Media", "Community Growth", "Meta Pixel", "Ad Optimization"],
    link: "https://www.coursera.org/professional-certificates/meta-social-media-marketing",
    domain: "Marketing",
    subDomain: "Social Media"
  },
  {
    id: "mkt-5",
    title: "Brand Identity, Strategy, and Strategic Storytelling Architect",
    platform: "Coursera",
    instructor: "Prof. Maria Harrison",
    rating: 4.8,
    learners: "90K+",
    duration: "15 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Branding Concepts", "Brand Architecture", "Competitive Moats", "Visual Design Tone"],
    link: "https://www.coursera.org/learn/brand-management",
    domain: "Marketing",
    subDomain: "Branding"
  },
  {
    id: "mkt-6",
    title: "Inbound Marketing & Lead Sourcing Strategy Certification",
    platform: "Coursera",
    instructor: "HubSpot Academy Experts",
    rating: 4.8,
    learners: "115K+",
    duration: "8 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Inbound Marketing", "Lead Capture Formulas", "SEO Copywriting", "CRM Integration"],
    link: "https://www.coursera.org/learn/brand-management",
    domain: "Marketing",
    subDomain: "Digital Marketing"
  },
  {
    id: "mkt-7",
    title: "Advanced Technical SEO & Schema Markup Deployment Blueprint",
    platform: "Udemy",
    instructor: "SEO Industry Academy",
    rating: 4.9,
    learners: "30K+",
    duration: "14 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Technical SEO", "Schema Markup", "Core Web Vitals", "Sitemap Audits"],
    link: "https://www.udemy.com/course/seo-get-targeted-traffic-to-your-website-optimized/",
    domain: "Marketing",
    subDomain: "SEO"
  },
  {
    id: "mkt-8",
    title: "Copywriting Masterclass: Powering High Converting Landing Pages",
    platform: "Udemy",
    instructor: "Tamsin Henderson",
    rating: 4.9,
    learners: "140K+",
    duration: "6 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["AIDA Copywriting Framework", "Headline Psychology", "Value Propositions", "Call-to-Action Tuning"],
    link: "https://www.udemy.com/course/learn-digital-marketing-course/",
    domain: "Marketing",
    subDomain: "Digital Marketing"
  },
  {
    id: "mkt-9",
    title: "Meta Ads & Programmatic Media Retargeting Strategies",
    platform: "Coursera",
    instructor: "Meta Business Blueprint Team",
    rating: 4.8,
    learners: "210K+",
    duration: "25 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Meta Ads Manager", "A/B Multivariate Testing", "Lookalike Audiences", "LTV Retargeting"],
    link: "https://www.coursera.org/professional-certificates/meta-social-media-marketing",
    domain: "Marketing",
    subDomain: "Social Media"
  },
  {
    id: "mkt-10",
    title: "Digital Marketing Metrics, Web KPIs & ROI Dashboards",
    platform: "Coursera",
    instructor: "Wharton Business School",
    rating: 4.8,
    learners: "85K+",
    duration: "12 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Marketing Attribution", "Customer Acquisition Cost (CAC)", "LTV Modeling", "ROI Calculations"],
    link: "https://www.coursera.org/learn/google-analytics",
    domain: "Marketing",
    subDomain: "Analytics"
  },
  {
    id: "mkt-11",
    title: "International Brand Strategy & Localization Campaign Design",
    platform: "Coursera",
    instructor: "London Business School Faculty",
    rating: 4.7,
    learners: "45K+",
    duration: "18 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Localization Campaigns", "Cross-Border Branding", "Niche Scaling", "Cultural Sensitivities"],
    link: "https://www.coursera.org/learn/brand-management",
    domain: "Marketing",
    subDomain: "Branding"
  },
  {
    id: "mkt-12",
    title: "YouTube Growth Masterclass & Organic Video SEO Strategy",
    platform: "YouTube",
    instructor: "Traversy Media & Guests",
    rating: 4.7,
    learners: "300K+",
    duration: "5 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Video SEO", "YouTube Algorithm Mechanics", "Ctr Optimization", "Engagement Metrics"],
    link: "https://www.youtube.com/results?search_query=learn+seo+marketing+tutorial",
    domain: "Marketing",
    subDomain: "SEO"
  },
  {
    id: "mkt-13",
    title: "Automated B2B Email Marketing Flows & Hubspot Campaigns",
    platform: "Udemy",
    instructor: "B2B Strategic Partners",
    rating: 4.8,
    learners: "65K+",
    duration: "8 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Drip Campaigns Setup", "Cold Outreach Protocols", "CRM Trigger Flowcharts", "Spam Filter Avoidance"],
    link: "https://www.udemy.com/course/learn-digital-marketing-course/",
    domain: "Marketing",
    subDomain: "Digital Marketing"
  },
  {
    id: "mkt-14",
    title: "LinkedIn Ads Strategy and Organic Executive Authority Scaling",
    platform: "Coursera",
    instructor: "LinkedIn Marketing Lab experts",
    rating: 4.8,
    learners: "40K+",
    duration: "10 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["LinkedIn Campaign Manager", "Account-Based Marketing (ABM)", "Professional Demographics Filtering", "Direct Sponsored Messaging"],
    link: "https://www.coursera.org/professional-certificates/meta-social-media-marketing",
    domain: "Marketing",
    subDomain: "Social Media"
  },
  {
    id: "mkt-15",
    title: "Brand Auditing & Corporate Reputation Crisis Management",
    platform: "Coursera",
    instructor: "IE Business School Premium Experts",
    rating: 4.9,
    learners: "52K+",
    duration: "15 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Reputation Metrics Tracking", "Crisis Communication Plans", "Sentiment Listening Tools", "Brand Equity Recovery"],
    link: "https://www.coursera.org/learn/brand-management",
    domain: "Marketing",
    subDomain: "Branding"
  },
  {
    id: "mkt-16",
    title: "Growth Hacking Methodology for High Traction Startups",
    platform: "Udemy",
    instructor: "Sean Ellis Academy",
    rating: 4.9,
    learners: "95K+",
    duration: "14 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Pirate Metrics (AARRR)", "Growth Sprints Scheduling", "Virality Index Modeling", "Retention Loop Funnels"],
    link: "https://www.udemy.com/course/learn-digital-marketing-course/",
    domain: "Marketing",
    subDomain: "Digital Marketing"
  },
  {
    id: "mkt-17",
    title: "App Store Optimization (ASO) & Premium Mobile Growth Systems",
    platform: "Udemy",
    instructor: "Mobile Action Experts",
    rating: 4.7,
    learners: "28K+",
    duration: "11 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["ASO Keyword Optimization", "Storefront Conversion Optimization", "Deep-linking Schemes", "App Store Metrics Analytics"],
    link: "https://www.udemy.com/course/seo-get-targeted-traffic-to-your-website-optimized/",
    domain: "Marketing",
    subDomain: "SEO"
  },
  {
    id: "mkt-18",
    title: "Predictive Analytics, Machine Learning & Python for Modern Marketers",
    platform: "Coursera",
    instructor: "Wharton Business Analytics Team",
    rating: 4.8,
    learners: "72K+",
    duration: "24 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Predictive Analytics", "Cohort Churn Models", "Python Pandas Marketing", "Multi-Touch Attribution"],
    link: "https://www.coursera.org/learn/google-analytics",
    domain: "Marketing",
    subDomain: "Analytics"
  },
  {
    id: "mkt-19",
    title: "Customer Journey Mapping Methodology & Retention Frameworks",
    platform: "Udemy",
    instructor: "UX/CX Designers Alliance",
    rating: 4.8,
    learners: "45K+",
    duration: "7 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Customer Journey Maps", "Net Promoter Score Tracking", "Friction Point Auditing", "Loyalty Multipliers Builder"],
    link: "https://www.udemy.com/course/learn-digital-marketing-course/",
    domain: "Marketing",
    subDomain: "Branding"
  },
  {
    id: "mkt-20",
    title: "Google Tag Manager (GTM) Infrastructure Setup Masterclass",
    platform: "Udemy",
    instructor: "Julius Fedorovicius",
    rating: 4.9,
    learners: "88K+",
    duration: "16 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["GTM Tags/Triggers Setup", "Datalayer Variables configuration", "E-Commerce tracking APIs", "Third-party Pixels Management"],
    link: "https://www.udemy.com/course/seo-get-targeted-traffic-to-your-website-optimized/",
    domain: "Marketing",
    subDomain: "Analytics"
  },
  {
    id: "mkt-21",
    title: "Brand Equity Modeling: Interbrand Methodology Blueprint",
    platform: "Coursera",
    instructor: "Vanderbilt University Faculty",
    rating: 4.7,
    learners: "37K+",
    duration: "12 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Brand Valuation Formulas", "Financial Brand Strength Index", "Ecosystem Value Capture", "Perpetual Intangibles Metrics"],
    link: "https://www.coursera.org/learn/brand-management",
    domain: "Marketing",
    subDomain: "Branding"
  },
  {
    id: "mkt-22",
    title: "Product Marketing Fundamentals: Product Launch Launchpads",
    platform: "Coursera",
    instructor: "Product Marketing Alliance",
    rating: 4.9,
    learners: "64K+",
    duration: "18 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Go-to-Market Strategy (GTM)", "Competitive Positioning Arrays", "Sales Enablement Matrices", "Messaging Hierarchy Design"],
    link: "https://www.coursera.org/learn/brand-management",
    domain: "Marketing",
    subDomain: "Digital Marketing"
  },
  {
    id: "mkt-23",
    title: "Neuro-Marketing & Cognitive Behavioral Economics of Advertisements",
    platform: "Coursera",
    instructor: "Copenhagen Business School Faculty",
    rating: 4.8,
    learners: "79K+",
    duration: "20 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Neuromarketing Testing", "Biometric Advertising Feedback", "Prospect Decision Theory", "Attention Retention Mechanics"],
    link: "https://www.coursera.org/learn/google-analytics",
    domain: "Marketing",
    subDomain: "Analytics"
  },
  {
    id: "mkt-24",
    title: "Influencer Campaign Sourcing Strategies & ROI Auditing",
    platform: "Udemy",
    instructor: "Viral Branding Guild",
    rating: 4.6,
    learners: "41K+",
    duration: "9 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Macro/Micro Influencer Sourcing", "Contracts Negotiation Schemes", "UTM Performance Tracking", "Engagement Auditing Procedures"],
    link: "https://www.udemy.com/course/learn-digital-marketing-course/",
    domain: "Marketing",
    subDomain: "Social Media"
  },
  {
    id: "mkt-25",
    title: "Advanced SEO Copywriting for AI Search Engine Optimizations",
    platform: "Udemy",
    instructor: "SEO Industry Academy Experts",
    rating: 4.8,
    learners: "53K+",
    duration: "10 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Semantic Web Copywriting", "Keyword Intent Mapping", "AI Engine Crawlability Design", "Featured Snippet Markups"],
    link: "https://www.udemy.com/course/seo-get-targeted-traffic-to-your-website-optimized/",
    domain: "Marketing",
    subDomain: "SEO"
  },

  // ==================== HR (25 Courses) ====================
  {
    id: "hr-1",
    title: "Talent Acquisition, Modern Recruitment & Expert Sourcing Strategies",
    platform: "Coursera",
    instructor: "Prof. Angela Patterson",
    rating: 4.8,
    learners: "110K+",
    duration: "13 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Recruitment funnel", "Candidate sourcing", "Active interviewing", "Pipeline management"],
    link: "https://www.coursera.org/learn/recruitment-and-sourcing",
    domain: "HR",
    subDomain: "Recruitment"
  },
  {
    id: "hr-2",
    title: "Human Resource Management Specialist Core Certification",
    platform: "Coursera",
    instructor: "University of Minnesota Faculty",
    rating: 4.9,
    learners: "340K+",
    duration: "5 Months",
    level: "Intermediate",
    certificate: "Available",
    skills: ["HR Strategy", "Employee Onboarding", "Performance Management", "Company Culture Alignment"],
    link: "https://www.coursera.org/specializations/human-resource-management",
    domain: "HR",
    subDomain: "Talent Acquisition"
  },
  {
    id: "hr-3",
    title: "Payroll Management & Compensation Structuring Mastery",
    platform: "Udemy",
    instructor: "Amman Ahmed",
    rating: 4.7,
    learners: "85K+",
    duration: "18 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Payroll Processing", "Benefits Design", "Tax Rules Alignment", "SLA Salary Models"],
    link: "https://www.udemy.com/course/uk-payroll-masterclass-training/",
    domain: "HR",
    subDomain: "HR Analytics"
  },
  {
    id: "hr-4",
    title: "Employee Engagement, Corporate Culture & Hybrid Teams Leadership",
    platform: "Udemy",
    instructor: "Vikas Jolly",
    rating: 4.8,
    learners: "95K+",
    duration: "14 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Engagement Tactics", "Conflict Resolution", "Interpersonal Skills", "Hybrid Working Models"],
    link: "https://www.udemy.com/course/employee-engagement-training/",
    domain: "HR",
    subDomain: "Leadership"
  },
  {
    id: "hr-5",
    title: "HR Analytics: Data-driven Decisions with Excel & Tableau Tools",
    platform: "Coursera",
    instructor: "Workforce Analytics Guild",
    rating: 4.8,
    learners: "150K+",
    duration: "25 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Workforce Analytics", "Predictive Churn Models", "KPI Dashboards", "Retention Metrics"],
    link: "https://www.coursera.org/learn/hr-analytics",
    domain: "HR",
    subDomain: "HR Analytics"
  },
  {
    id: "hr-6",
    title: "High Performance Recruiting: Sourcing Candidates on LinkedIn",
    platform: "Udemy",
    instructor: "Job Hunt Alliance Professionals",
    rating: 4.8,
    learners: "70K+",
    duration: "8 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["LinkedIn Recruiter Premium", "Boolean Sourcing Strings", "InMail Outreach Optimization", "Employer Branding"],
    link: "https://www.udemy.com/course/uk-payroll-masterclass-training/",
    domain: "HR",
    subDomain: "Recruitment"
  },
  {
    id: "hr-7",
    title: "Strategic HR Leadership: Structuring Modern Global Organizations",
    platform: "Coursera",
    instructor: "Wharton Business School Executives",
    rating: 4.9,
    learners: "120K+",
    duration: "4 Months",
    level: "Advanced",
    certificate: "Available",
    skills: ["Strategic Re-orgs", "Talent Planning Protocols", "Corporate Change Execution", "Executive HR Partnering"],
    link: "https://www.coursera.org/specializations/human-resource-management",
    domain: "HR",
    subDomain: "Leadership"
  },
  {
    id: "hr-8",
    title: "Employment Law compliance & Workplace Safety Mandates",
    platform: "Udemy",
    instructor: "Legal Compliance Partners",
    rating: 4.7,
    learners: "55K+",
    duration: "12 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Labor Laws Compliance", "Arbitration Procedures", "OSHA Safeguards", "Title VII Anti-Discrimination"],
    link: "https://www.udemy.com/course/uk-payroll-masterclass-training/",
    domain: "HR",
    subDomain: "Talent Acquisition"
  },
  {
    id: "hr-9",
    title: "Diversity, Equity, and Inclusion (DEI) Corporate Architect",
    platform: "Coursera",
    instructor: "ESSEC Business School Faculty",
    rating: 4.8,
    learners: "88K+",
    duration: "16 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["DEI Strategy", "Unconscious Bias Mitigation", "Inclusive Job Specs", "Representative Recruitment Pipeline"],
    link: "https://www.coursera.org/learn/recruitment-and-sourcing",
    domain: "HR",
    subDomain: "Talent Acquisition"
  },
  {
    id: "hr-10",
    title: "Excel Data Sheets and Pivot Reporting for HR Managers",
    platform: "Udemy",
    instructor: "Kyle Pew",
    rating: 4.8,
    learners: "210K+",
    duration: "10 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Excel HR Calculations", "Attendance Macros", "Salary Modeling Matrices", "Pivot Tables Reporting"],
    link: "https://www.udemy.com/course/uk-payroll-masterclass-training/",
    domain: "HR",
    subDomain: "HR Analytics"
  },
  {
    id: "hr-11",
    title: "Advanced Interview Techniques & Forensic Candidate Assessment",
    platform: "Coursera",
    instructor: "PwC Consulting Academy Experts",
    rating: 4.9,
    learners: "67K+",
    duration: "15 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Structured Interview Auditing", "Behavioral Calibration Metrics", "STAR Response Scoring", "Executive Assessment Schemes"],
    link: "https://www.coursera.org/learn/recruitment-and-sourcing",
    domain: "HR",
    subDomain: "Recruitment"
  },
  {
    id: "hr-12",
    title: "Employer Branding and Candidate Recruitment Marketing Core",
    platform: "Udemy",
    instructor: "Corporate Brand Consultants",
    rating: 4.7,
    learners: "38K+",
    duration: "7 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Candidate Value Proposition", "Glassdoor Rating Strategy", "Social Media Sourcing Funnels", "Careers Page SEO"],
    link: "https://www.udemy.com/course/uk-payroll-masterclass-training/",
    domain: "HR",
    subDomain: "Recruitment"
  },
  {
    id: "hr-13",
    title: "Conflict Management & Negotiation Tactics in Corporate HR",
    platform: "Coursera",
    instructor: "University of Michigan Team",
    rating: 4.9,
    learners: "145K+",
    duration: "18 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Dispute Escalation Protocols", "Negotiation Frameworks", "Active Listening Systems", "Win-Win Agreements Crafting"],
    link: "https://www.coursera.org/specializations/human-resource-management",
    domain: "HR",
    subDomain: "Leadership"
  },
  {
    id: "hr-14",
    title: "Organisational Psychology: Managing Team Performance Gaps",
    platform: "Coursera",
    instructor: "Prof. Kenneth George",
    rating: 4.8,
    learners: "92K+",
    duration: "20 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Group Dynamics Theories", "Motivation Incentives Analysis", "Psychological Safety Metrics", "Behavioral Coaching Procedures"],
    link: "https://www.coursera.org/specializations/human-resource-management",
    domain: "HR",
    subDomain: "Leadership"
  },
  {
    id: "hr-15",
    title: "Workforce Planning, Scheduling & HR Succession Modeling",
    platform: "Udemy",
    instructor: "Workforce Solutions Hub",
    rating: 4.8,
    learners: "45K+",
    duration: "12 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Staffing Gap Assessments", "Succession Probability Charts", "Skill Mapping Databases", "Frictional Churn Forecasts"],
    link: "https://www.udemy.com/course/uk-payroll-masterclass-training/",
    domain: "HR",
    subDomain: "HR Analytics"
  },
  {
    id: "hr-16",
    title: "Employee Onboarding System Design: Fostering Day-One Ingress",
    platform: "Udemy",
    instructor: "Alex S. Mercer",
    rating: 4.8,
    learners: "32K+",
    duration: "9 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Onboarding Flowcharts", "New-hire Portal Integrations", "First-month Mentorship Systems", "Frictionless Documentation Processes"],
    link: "https://www.udemy.com/course/onboarding-employee-experience/",
    domain: "HR",
    subDomain: "Talent Acquisition"
  },
  {
    id: "hr-17",
    title: "Performance Review Infrastructure & Feedback Calibrations",
    platform: "Coursera",
    instructor: "IE Business School Professionals",
    rating: 4.8,
    learners: "135K+",
    duration: "11 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["KPI Definitions Sourcing", "OKR Cadence Setup", "360-degree Review Models", "Performance Alignment Schemes"],
    link: "https://www.coursera.org/specializations/human-resource-management",
    domain: "HR",
    subDomain: "Leadership"
  },
  {
    id: "hr-18",
    title: "Strategic Talent Management & Global Mobility Architecture",
    platform: "Coursera",
    instructor: "Erasmus University Faculty",
    rating: 4.7,
    learners: "29K+",
    duration: "16 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Global Relocation Visas", "Expat Compensation Plans", "Remote Workforce Compliance", "Tax Arbitrage Alignment"],
    link: "https://www.coursera.org/specializations/human-resource-management",
    domain: "HR",
    subDomain: "Talent Acquisition"
  },
  {
    id: "hr-19",
    title: "HRIS Database Operations & Oracle HCM Systems Roadmap",
    platform: "Udemy",
    instructor: "Enterprise ERP Academy",
    rating: 4.6,
    learners: "54K+",
    duration: "24 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Oracle HCM Integration", "Employee Data Security Standards", "Access Control Auditing", "Automated Payroll Feeds"],
    link: "https://www.udemy.com/course/uk-payroll-masterclass-training/",
    domain: "HR",
    subDomain: "HR Analytics"
  },
  {
    id: "hr-20",
    title: "Executive Search and Technical Recruitment Masterclass",
    platform: "Udemy",
    instructor: "DevRecruit Specialists",
    rating: 4.9,
    learners: "41K+",
    duration: "15 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Technical Vetting Sheets", "Executive Retainer Structures", "Non-compete Contract Interpretation", "C-suite Headhunting Strategies"],
    link: "https://www.udemy.com/course/uk-payroll-masterclass-training/",
    domain: "HR",
    subDomain: "Recruitment"
  },
  {
    id: "hr-21",
    title: "Labor Relations, Trade Unions and Collective Bargaining Strategy",
    platform: "Coursera",
    instructor: "Rutgers University Labor Team",
    rating: 4.7,
    learners: "25K+",
    duration: "20 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Union Contract Negotiations", "Collective Bargaining Agreements", "Grievance Redressal Mechanisms", "Industrial Dispute Codes"],
    link: "https://www.coursera.org/specializations/human-resource-management",
    domain: "HR",
    subDomain: "Talent Acquisition"
  },
  {
    id: "hr-22",
    title: "Mental Health Initiatives, Wellness Schemes and Employee Care",
    platform: "Udemy",
    instructor: "Mindfulness @ Work Trainers",
    rating: 4.8,
    learners: "65K+",
    duration: "6 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["EAP Schemes Deployment", "Stress Containment Seminars", "Workplace Burnout Indicators", "Mental Well-being Policies"],
    link: "https://www.udemy.com/course/employee-engagement-training/",
    domain: "HR",
    subDomain: "Leadership"
  },
  {
    id: "hr-23",
    title: "People Analytics: Transforming HR with Python & R Scripting",
    platform: "Coursera",
    instructor: "Professor Dave Ulrich",
    rating: 4.9,
    learners: "47K+",
    duration: "30 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["R Studio People Analysis", "Clustering Attrition Profiles", "Survival Analysis Algorithms", "Labor Pricing Forecasting"],
    link: "https://www.coursera.org/learn/hr-analytics",
    domain: "HR",
    subDomain: "HR Analytics"
  },
  {
    id: "hr-24",
    title: "Effective On-the-Job Mentorship & Skill Transfer Systems",
    platform: "Udemy",
    instructor: "Workforce Upskilling Network",
    rating: 4.7,
    learners: "19K+",
    duration: "10 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Apprenticeship Structuring", "Cross-Training Matrices", "Constructive Feedback Sheets", "Peer Evaluation Scales"],
    link: "https://www.udemy.com/course/onboarding-employee-experience/",
    domain: "HR",
    subDomain: "Talent Acquisition"
  },
  {
    id: "hr-25",
    title: "Modern HR Tech Ecosystems: Integration and APIs Strategy",
    platform: "Udemy",
    instructor: "SaaS Ecosystem Advisors",
    rating: 4.8,
    learners: "15K+",
    duration: "12 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["ATS Splicing", "REST Webhooks integration", "Zapier HR flows", "SaaS SSO setup"],
    link: "https://www.udemy.com/course/uk-payroll-masterclass-training/",
    domain: "HR",
    subDomain: "HR Analytics"
  },

  // ==================== MBA/BUSINESS (25 Courses) ====================
  {
    id: "mba-1",
    title: "Product Management complete guide: Agile, Scrum & Prototypes",
    platform: "Udemy",
    instructor: "Cole Mercer",
    rating: 4.9,
    learners: "510K+",
    duration: "25 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Agile Development", "User Stories", "Product Roadmaps", "Wireframing MVP", "Scrum Framework"],
    link: "https://www.udemy.com/course/the-one-week-technical-pm-course/",
    domain: "MBA/Business",
    subDomain: "Product Management"
  },
  {
    id: "mba-2",
    title: "Management Consulting Masterclass: McKinsey Presentation Frameworks",
    platform: "Udemy",
    instructor: "John Kim (Ex-Deloitte Partner)",
    rating: 4.8,
    learners: "85K+",
    duration: "15 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["MECE Structuring", "Case Interview Tactics", "Slide Desigining", "Strategic Recommendations"],
    link: "https://www.udemy.com/course/management-consulting-essential-training/",
    domain: "MBA/Business",
    subDomain: "Consulting"
  },
  {
    id: "mba-3",
    title: "Operations Management: Supply Chain & Six Sigma Frameworks",
    platform: "Coursera",
    instructor: "Wharton Operations Team",
    rating: 4.8,
    learners: "180K+",
    duration: "4 Months",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Six Sigma Methods", "Inventory Control Models", "Logistics Planning", "Bottleneck Identifications"],
    link: "https://www.coursera.org/specializations/wharton-operations-analytics",
    domain: "MBA/Business",
    subDomain: "Operations"
  },
  {
    id: "mba-4",
    title: "Business Analytics Specialization: Analytics-Driven Operations",
    platform: "Coursera",
    instructor: "Wharton Business School Analysts",
    rating: 4.9,
    learners: "280K+",
    duration: "5 Months",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Business Intellligence", "Descriptive Analytics", "Linear Programming", "Forecasting Matrices"],
    link: "https://www.coursera.org/specializations/business-analytics",
    domain: "MBA/Business",
    subDomain: "Business Analytics"
  },
  {
    id: "mba-5",
    title: "Strategic Management: Building Competitive Business Tactics",
    platform: "Coursera",
    instructor: "Copenhagen Business School",
    rating: 4.8,
    learners: "140K+",
    duration: "18 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Porter's Five Forces", "SWOT Calibration", "Blue Ocean Strategy", "Mergers Integration"],
    link: "https://www.coursera.org/learn/strategic-management",
    domain: "MBA/Business",
    subDomain: "Consulting"
  },
  {
    id: "mba-6",
    title: "Product Owner Core: Agile Scrum Mastery and Backlog Grooming",
    platform: "Udemy",
    instructor: "Scrum Alliance Instructors",
    rating: 4.8,
    learners: "92K+",
    duration: "11 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["User Persona Mapping", "Epic Sizing", "Backlog Prioritization", "Stakeholder Communications"],
    link: "https://www.udemy.com/course/the-one-week-technical-pm-course/",
    domain: "MBA/Business",
    subDomain: "Product Management"
  },
  {
    id: "mba-7",
    title: "Supply Chain Logistics & Global Distribution Management Blueprint",
    platform: "Coursera",
    instructor: "Rutgers University Logistics Team",
    rating: 4.7,
    learners: "98K+",
    duration: "30 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Warehouse Inventory Flow", "Incoterms Controls", "Route Visualizations", "Sourcing Logistics"],
    link: "https://www.coursera.org/specializations/wharton-operations-analytics",
    domain: "MBA/Business",
    subDomain: "Operations"
  },
  {
    id: "mba-8",
    title: "Data-Driven Business Analytics using SQL and Tableau Tools",
    platform: "Udemy",
    instructor: "Kirill Eremenko",
    rating: 4.8,
    learners: "220K+",
    duration: "21 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Tableau BI Charts", "SQL Group Joins", "Cohort Trendlines", "Interactive Dashboarding"],
    link: "https://www.udemy.com/course/tableau10/",
    domain: "MBA/Business",
    subDomain: "Business Analytics"
  },
  {
    id: "mba-9",
    title: "Project Management core: Principles and PMBOK Boot Camp",
    platform: "Udemy",
    instructor: "Joseph Phillips (PMP® Mentor)",
    rating: 4.8,
    learners: "320K+",
    duration: "35 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Critical Path Method", "Earned Value Management", "Project Charter Generation", "Resource Allocations"],
    link: "https://www.udemy.com/course/management-consulting-essential-training/",
    domain: "MBA/Business",
    subDomain: "Operations"
  },
  {
    id: "mba-10",
    title: "Case Interview Secrets: Crack Consulting Firm Recruitment",
    platform: "Udemy",
    instructor: "Ex-McKinsey Consulting Reviewers",
    rating: 4.9,
    learners: "55K+",
    duration: "10 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Case Math Drills", "Interactive Breakouts", "Framework Assembly", "Profitability Trees"],
    link: "https://www.udemy.com/course/management-consulting-essential-training/",
    domain: "MBA/Business",
    subDomain: "Consulting"
  },
  {
    id: "mba-11",
    title: "Advanced Product Tactics: Metrics, Kpis, and A/B Testing Design",
    platform: "Coursera",
    instructor: "Johns Hopkins University Faculty",
    rating: 4.8,
    learners: "70K+",
    duration: "15 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["A/B Hypothesis Testing", "North Star Metrics", "Cohorts Churn Diagnostics", "User Engagement Loops"],
    link: "https://www.coursera.org/learn/strategic-management",
    domain: "MBA/Business",
    subDomain: "Product Management"
  },
  {
    id: "mba-12",
    title: "Total Quality Management (TQM) & Lean Six Sigma Certification",
    platform: "Udemy",
    instructor: "Quality Engineering Academy Experts",
    rating: 4.7,
    learners: "130K+",
    duration: "18 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Lean DMAIC Cycle", "Ishikawa Diagrams", "Pareto Distributions Analysis", "Process Capabilities (Cp/Cpk)"],
    link: "https://www.udemy.com/course/management-consulting-essential-training/",
    domain: "MBA/Business",
    subDomain: "Operations"
  },
  {
    id: "mba-13",
    title: "Financial Business Intelligence: DAX Models under Power BI",
    platform: "Coursera",
    instructor: "Microsoft Press Analyst Team",
    rating: 4.8,
    learners: "115K+",
    duration: "24 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["DAX Matrix Modeling", "Sales Trend Forecasts", "Inventory Reporting dashboards", "Power Query Formulas"],
    link: "https://www.coursera.org/specializations/business-analytics",
    domain: "MBA/Business",
    subDomain: "Business Analytics"
  },
  {
    id: "mba-14",
    title: "Strategic Consulting: Business Mergers & Valuation Cases",
    platform: "Coursera",
    instructor: "Wharton Finance Executives",
    rating: 4.8,
    learners: "65K+",
    duration: "12 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["M&A Consolidation Tactics", "Accretion/Dilution Analysis", "Strategic Synergies Calculations", "Transaction Pricing Cases"],
    link: "https://www.coursera.org/learn/strategic-management",
    domain: "MBA/Business",
    subDomain: "Consulting"
  },
  {
    id: "mba-15",
    title: "Product Road-mapping: Design to Engineering Pipelines Integration",
    platform: "Udemy",
    instructor: "ProdPad Product Founders",
    rating: 4.8,
    learners: "45K+",
    duration: "8 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Release Scheduling Tools", "Engineering JIRA alignment", "Customer Feedback Prioritizers", "GTM Communication Sheets"],
    link: "https://www.udemy.com/course/the-one-week-technical-pm-course/",
    domain: "MBA/Business",
    subDomain: "Product Management"
  },
  {
    id: "mba-16",
    title: "Factory Operations & Global Manufacturing Cost Optimizations",
    platform: "Coursera",
    instructor: "Munich Technical University",
    rating: 4.7,
    learners: "33K+",
    duration: "20 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Kanban Loops Automation", "Lead Time Compression", "MRP System Audits", "Asset Utilization Metrics"],
    link: "https://www.coursera.org/specializations/wharton-operations-analytics",
    domain: "MBA/Business",
    subDomain: "Operations"
  },
  {
    id: "mba-17",
    title: "Predictive Business Modeling using Python Pandas and Scikit-learn",
    platform: "Coursera",
    instructor: "Wharton Business Analytics Faculty",
    rating: 4.9,
    learners: "85K+",
    duration: "28 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Regression Forecasting", "Clustering Segments Analysis", "Sales Forecasting Python Scripts", "Scikit ML Estimators"],
    link: "https://www.coursera.org/specializations/business-analytics",
    domain: "MBA/Business",
    subDomain: "Business Analytics"
  },
  {
    id: "mba-18",
    title: "The McKinsey Problem Solving Test (PST) Ultimate Cracker",
    platform: "Udemy",
    instructor: "Firm Sourcing Specialists",
    rating: 4.9,
    learners: "25K+",
    duration: "14 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Graph Interpretations Drills", "Business Logical Splicing", "Quantitative Approximations", "Time Constraint Optimization"],
    link: "https://www.udemy.com/course/management-consulting-essential-training/",
    domain: "MBA/Business",
    subDomain: "Consulting"
  },
  {
    id: "mba-19",
    title: "Technical Product Management: APIs, System Design, SQL",
    platform: "Udemy",
    instructor: "Tech PM Academy Team",
    rating: 4.8,
    learners: "80K+",
    duration: "18 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["API Blueprint Reading", "REST Integrations Splicing", "Database ERD schemas", "System Cost Modeling"],
    link: "https://www.udemy.com/course/the-one-week-technical-pm-course/",
    domain: "MBA/Business",
    subDomain: "Product Management"
  },
  {
    id: "mba-20",
    title: "Procurement Management, Vendor Sourcing & RFPs Structuring",
    platform: "Udemy",
    instructor: "Logistics Academy experts",
    rating: 4.7,
    learners: "41K+",
    duration: "12 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["RFP Response Templates", "Vendor Evaluation Matrix", "SLA Negotiations", "Contract Pricing Schedules"],
    link: "https://www.udemy.com/course/management-consulting-essential-training/",
    domain: "MBA/Business",
    subDomain: "Operations"
  },
  {
    id: "mba-21",
    title: "Business Process Re-Engineering and Flowcharts Audits",
    platform: "Coursera",
    instructor: "University of Illinois Faculty",
    rating: 4.8,
    learners: "65K+",
    duration: "15 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["BPMN Flowchart Standards", "Waste Reductions Auditing", "Value Add Checks", "As-Is / To-Be Mapping"],
    link: "https://www.coursera.org/specializations/wharton-operations-analytics",
    domain: "MBA/Business",
    subDomain: "Operations"
  },
  {
    id: "mba-22",
    title: "Market Entry Case Strategies and Competitive Moats Construction",
    platform: "Coursera",
    instructor: "Harvard Business School Educators",
    rating: 4.9,
    learners: "120K+",
    duration: "20 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Market Size Guesstimates", "Competitive Reaction Scenarios", "Regulatory Barrier Assessments", "Pricing Strategy Models"],
    link: "https://www.coursera.org/learn/strategic-management",
    domain: "MBA/Business",
    subDomain: "Consulting"
  },
  {
    id: "mba-23",
    title: "Sales Operations Strategy & Salesforce Analytics Dashboarding",
    platform: "Udemy",
    instructor: "Enterprise ERP Professionals",
    rating: 4.8,
    learners: "54K+",
    duration: "16 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Sales Pipeline Funneling", "Salesforce Reports Setup", "Quotas Adjustments Modeling", "Territory Mapping Tables"],
    link: "https://www.udemy.com/course/tableau10/",
    domain: "MBA/Business",
    subDomain: "Business Analytics"
  },
  {
    id: "mba-24",
    title: "Growth Product Management: Activation, Conversions & Funnels",
    platform: "Udemy",
    instructor: "Growth Hackers Alliance Experts",
    rating: 4.9,
    learners: "38K+",
    duration: "12 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["User Activation Loops", "Checkout Optimization Plans", "Funnel Drop-Off Analytics", "In-App Gamification Guides"],
    link: "https://www.udemy.com/course/the-one-week-technical-pm-course/",
    domain: "MBA/Business",
    subDomain: "Product Management"
  },
  {
    id: "mba-25",
    title: "Supply Chain Risk Management & Crisis Mitigation Protocols",
    platform: "Coursera",
    instructor: "Wharton Operations Division",
    rating: 4.8,
    learners: "47K+",
    duration: "14 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Sovereign Supply Sourcing", "Macro Shock Planning", "Dual Partner Redundancies", "Safety Stock Formulas"],
    link: "https://www.coursera.org/specializations/wharton-operations-analytics",
    domain: "MBA/Business",
    subDomain: "Operations"
  },

  // ==================== COMMERCE (25 Courses) ====================
  {
    id: "com-1",
    title: "Accounting Foundations: Double-Entry Ledgers & Balance Sheets",
    platform: "Coursera",
    instructor: "Wharton Business School Accounting",
    rating: 4.9,
    learners: "280K+",
    duration: "15 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Double-Entry Ledgers", "T-Accounts Journaling", "Income Statements Configuration", "Depreciations Schemes"],
    link: "https://www.coursera.org/learn/wharton-accounting",
    domain: "Commerce",
    subDomain: "Accounting"
  },
  {
    id: "com-2",
    title: "Corporate Taxation Laws & Strategic Auditing and compliance",
    platform: "Coursera",
    instructor: "University of Illinois Taxation",
    rating: 4.8,
    learners: "95K+",
    duration: "4 Months",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Corporate Tax Shields", "State Jurisdictions Codes", "Capital Gains Deductibles", "Tax Audit Tracing"],
    link: "https://www.coursera.org/specializations/federal-taxation",
    domain: "Commerce",
    subDomain: "Taxation"
  },
  {
    id: "com-3",
    title: "Investment Analysis & Corporate Securities Valuation Models",
    platform: "Udemy",
    instructor: "Dr. Manish Kumar",
    rating: 4.8,
    learners: "120K+",
    duration: "25 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["DCF Equity Models", "Dividend Discount Modeling", "Relative Valuation Factors", "WACC Cost Calculations"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Commerce",
    subDomain: "Investment Analysis"
  },
  {
    id: "com-4",
    title: "Forensic Accounting, Fraud Sourcing & Audits Management",
    platform: "Coursera",
    instructor: "West Virginia University",
    rating: 4.8,
    learners: "110K+",
    duration: "22 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Fraud Triangle Indicators", "Asset Misappropriation Tracing", "Audit Sampling Formulas", "Bank Recs Forgeries Checks"],
    link: "https://www.coursera.org/learn/forensic-accounting",
    domain: "Commerce",
    subDomain: "Accounting"
  },
  {
    id: "com-5",
    title: "VAT, GST, and International Indirect Consumption Tax Policies",
    platform: "Udemy",
    instructor: "International Tax Academy experts",
    rating: 4.7,
    learners: "45K+",
    duration: "10 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Value-Added Tax (VAT)", "GST Invoicing Protocols", "Cross-Border customs taxes", "Input Tax Credits Retrieval"],
    link: "https://www.udemy.com/course/financial-modeling-for-beginners/",
    domain: "Commerce",
    subDomain: "Taxation"
  },
  {
    id: "com-6",
    title: "Fixed Income Analysis: Pricing Bonds & Debt Portfolios",
    platform: "Udemy",
    instructor: "CFA Training Guild",
    rating: 4.8,
    learners: "65K+",
    duration: "16 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Yield to Maturity (YTM) Calculations", "Duration/Convexity Factor Calculations", "Credit Spreads Benchmarks", "Treasuries Pricing Formulas"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Commerce",
    subDomain: "Investment Analysis"
  },
  {
    id: "com-7",
    title: "Cost & Managerial Accounting Models for Industrial Factories",
    platform: "Coursera",
    instructor: "University of Pennsylvania",
    rating: 4.8,
    learners: "140K+",
    duration: "18 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Standard Costing variances", "Activity-Based Costing (ABC)", "Break-Even Margin matrices", "Cost Allocation Rules"],
    link: "https://www.coursera.org/learn/wharton-accounting",
    domain: "Commerce",
    subDomain: "Accounting"
  },
  {
    id: "com-8",
    title: "Individual Income Tax Return filing under Federal Statutes",
    platform: "Coursera",
    instructor: "Tax Academy of Illinois",
    rating: 4.8,
    learners: "70K+",
    duration: "20 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Form 1040 Preparation", "Adjusted Gross Income (AGI)", "Schedule C business filings", "Tax Bracket Calculations"],
    link: "https://www.coursera.org/specializations/federal-taxation",
    domain: "Commerce",
    subDomain: "Taxation"
  },
  {
    id: "com-9",
    title: "Ecosystems and Valuation of Real Estate Investment Trusts (REITs)",
    platform: "Udemy",
    instructor: "Real Estate Analyst Partners",
    rating: 4.7,
    learners: "35K+",
    duration: "12 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["FFO/AFFO Yield Calculations", "Net Asset Value (NAV) Appraisals", "REIT Tax Shields", "Mortgage-backed Securities Analysis"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Commerce",
    subDomain: "Investment Analysis"
  },
  {
    id: "com-10",
    title: "Consolidated Financial Accounting under IFRS & GAAP",
    platform: "Coursera",
    instructor: "University of London Specialists",
    rating: 4.9,
    learners: "85K+",
    duration: "30 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["IFRS Standards Alignment", "Inter-company Eliminations Sheets", "Non-controlling Interest Metrics", "Foreign Currency Consolidation"],
    link: "https://www.coursera.org/learn/wharton-accounting",
    domain: "Commerce",
    subDomain: "Accounting"
  },
  {
    id: "com-11",
    title: "Transfer Pricing Mechanics under Global Tax Statutes",
    platform: "Coursera",
    instructor: "Erasmus University Tax Law Team",
    rating: 4.8,
    learners: "28K+",
    duration: "14 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Arm's Length Principle", "Inter-company pricing formulas", "BEPS Multi-state Compliance", "Double Tax Treaties Interpretation"],
    link: "https://www.coursera.org/specializations/federal-taxation",
    domain: "Commerce",
    subDomain: "Taxation"
  },
  {
    id: "com-12",
    title: "Modern Derivative Pricing: Options, Swaps, Futuring models",
    platform: "Udemy",
    instructor: "Risk Analytics Specialists",
    rating: 4.9,
    learners: "72K+",
    duration: "22 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Black-Scholes Options Model", "Interest Swaps Agreements", "Delta Hedging Strategies", "Futures Margin Analysis"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Commerce",
    subDomain: "Investment Analysis"
  },
  {
    id: "com-13",
    title: "Audit Auditing Standards: Issuing Strategic Opinions and Reports",
    platform: "Coursera",
    instructor: "Wharton Audit Division Staff",
    rating: 4.8,
    learners: "130K+",
    duration: "25 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["GAAP Auditing Opinions", "Substantive Ledger Auditing", "Risk Assessment Frameworks", "C-Suite reporting briefs"],
    link: "https://www.coursera.org/learn/wharton-accounting",
    domain: "Commerce",
    subDomain: "Accounting"
  },
  {
    id: "com-14",
    title: "Sales Tax and Nexus Rules for modern E-Commerce Platforms",
    platform: "Udemy",
    instructor: "E-Commerce Accounting Alliance",
    rating: 4.7,
    learners: "41K+",
    duration: "9 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Economic Nexus Auditing", "Shipment Origin Taxing Rules", "Automated Shopify Tax Plugins", "Sales tax filings software"],
    link: "https://www.udemy.com/course/financial-modeling-for-beginners/",
    domain: "Commerce",
    subDomain: "Taxation"
  },
  {
    id: "com-15",
    title: "Equity Research Analysis: Preparing Equity Recommendation Briefs",
    platform: "Udemy",
    instructor: "Sell-Side Analyst Coaches",
    rating: 4.8,
    learners: "53K+",
    duration: "18 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Sell-side Reporting Format", "Eps Modeling Excel Scripts", "Ecosystem Pricing Drivers", "Equity Recommendations formulation"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Commerce",
    subDomain: "Investment Analysis"
  },
  {
    id: "com-16",
    title: "Accounting Databases, SQL and Sage Accounts ERP Systems",
    platform: "Udemy",
    instructor: "Enterprise Accounting ERP Team",
    rating: 4.6,
    learners: "65K+",
    duration: "20 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Sage Accounts Enterprise", "SQL Ledger Auditing", "Automated Journal Entries Macros", "ERP Access Logging"],
    link: "https://www.udemy.com/course/financial-modeling-for-beginners/",
    domain: "Commerce",
    subDomain: "Accounting"
  },
  {
    id: "com-17",
    title: "Cross-Border M&A Tax Restructuring and Corporate reorganizations",
    platform: "Coursera",
    instructor: "IE Business School Taxation Faculty",
    rating: 4.9,
    learners: "34K+",
    duration: "16 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Tax-Free reorganizations", "Stock buying taxation structures", "Asset purchase tax strategies", "Net Operating Loss carryforwards"],
    link: "https://www.coursera.org/specializations/federal-taxation",
    domain: "Commerce",
    subDomain: "Taxation"
  },
  {
    id: "com-18",
    title: "Venture Capital Term Sheets, Valuation models and Exit Cases",
    platform: "Udemy",
    instructor: "Venture Capitalists Training Hub",
    rating: 4.8,
    learners: "45K+",
    duration: "11 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Term sheet term valuations", "Liquidation preference multiples", "Anti-dilution triggers", "LTM Revenue valuation multiples"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Commerce",
    subDomain: "Investment Analysis"
  },
  {
    id: "com-19",
    title: "Small Business Accounting, Quickbooks and Basic Bookkeeping",
    platform: "Udemy",
    instructor: "Quickbooks Pro Trainers",
    rating: 4.8,
    learners: "190K+",
    duration: "8 Hours",
    level: "Beginner",
    certificate: "Available",
    skills: ["Quickbooks Pro setup", "Invoice generation flows", "Bank feeds auto-reconcile", "Quarterly estimates reporting"],
    link: "https://www.udemy.com/course/financial-modeling-for-beginners/",
    domain: "Commerce",
    subDomain: "Accounting"
  },
  {
    id: "com-20",
    title: "Customs Taxation, Tariffs Rules and Global Supply Logistics",
    platform: "Coursera",
    instructor: "Erasmus University Customs Guild",
    rating: 4.7,
    learners: "22K+",
    duration: "13 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Harmonized Tariff (HTS) Codes", "Customs Appraisal Methods", "Anti-dumping penalties", "Bonded Warehouse Taxing"],
    link: "https://www.coursera.org/specializations/federal-taxation",
    domain: "Commerce",
    subDomain: "Taxation"
  },
  {
    id: "com-21",
    title: "Strategic Asset Pricing: Capital Asset Pricing Model (CAPM) and Arbitrage Theory",
    platform: "Udemy",
    instructor: "Dr. Manish Kumar",
    rating: 4.8,
    learners: "39K+",
    duration: "14 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["CAPM Index Pricing", "Fama-French Factor Models", "Arbitrage Pricing Theory", "Stochastic Valuation Factor"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Commerce",
    subDomain: "Investment Analysis"
  },
  {
    id: "com-22",
    title: "Government and Non-Profit Ledger Accounting Standards",
    platform: "Coursera",
    instructor: "University of Illinois Public Finance",
    rating: 4.8,
    learners: "43K+",
    duration: "24 Hours",
    level: "Intermediate",
    certificate: "Available",
    skills: ["Fund Ledger Accounting", "GASB Reporting Rules", "State and Local Gov Budgeting", "Encumbrance Ledger Auditing"],
    link: "https://www.coursera.org/learn/wharton-accounting",
    domain: "Commerce",
    subDomain: "Accounting"
  },
  {
    id: "com-23",
    title: "IRS Auditing Defense, Practices and Resolution Tactics",
    platform: "Udemy",
    instructor: "CPA/Enrolled Agent Defense Academy",
    rating: 4.9,
    learners: "18K+",
    duration: "12 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["IRS Audits Representation", "Statute of Limitations Defense", "Offer in Compromise (OIC)", "IRS Tax Appeal protocols"],
    link: "https://www.udemy.com/course/financial-modeling-for-beginners/",
    domain: "Commerce",
    subDomain: "Taxation"
  },
  {
    id: "com-24",
    title: "Macro Currency Arbitrage, Forex Markets Valuation and Mechanics",
    platform: "Udemy",
    instructor: "Sell-Side Currency Structurers",
    rating: 4.7,
    learners: "61K+",
    duration: "15 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["Purchase Power Parity (PPP)", "Forward Premia Calculations", "Interest Rate Arbitrage Index", "Cross-currency Balance of Trade"],
    link: "https://www.udemy.com/course/investment-analysis-portfolio-management/",
    domain: "Commerce",
    subDomain: "Investment Analysis"
  },
  {
    id: "com-25",
    title: "IFRS 16 Lease accounting standards & Excel model worksheets",
    platform: "Udemy",
    instructor: "Wall Street Prep Experts",
    rating: 4.8,
    learners: "29K+",
    duration: "10 Hours",
    level: "Advanced",
    certificate: "Available",
    skills: ["IFRS 16 Lease Standards", "Right-of-Use Asset calculations", "Lease Liability scheduling", "GAAP Dual Classification Worksheets"],
    link: "https://www.udemy.com/course/financial-modeling-for-beginners/",
    domain: "Commerce",
    subDomain: "Accounting"
  }
];
